version: '3.8'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmp_app
    #command: npm run dev
    ports:
      - "8081:3000"
    environment:
      NODE_ENV: development